---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: app
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app-container
        image: app:libcluster
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: HOST
          value: localhost
        - name: ERLANG_COOKIE
          value: secret
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command: ["elixir"]
        args: [
          "--name", "app@$(POD_IP)",
          "--cookie", "$(ERLANG_COOKIE)",
          "--no-halt",
          "-S", "mix", "app.start"
        ]

---
kind: Service
apiVersion: v1

metadata:
  name: app
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - name: http
      port: 8000
      targetPort: 4000

---
kind: Service
apiVersion: v1

metadata:
  name: app-nodes
  namespace: default
spec:
  clusterIP: None
  selector:
    app: app
  ports:
    - name: epmd
      port: 4369
